// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package userclient

import (
	"context"

	"microservice/user/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DataResponse           = user.DataResponse
	RegisterOrLoginRequest = user.RegisterOrLoginRequest
	UserData               = user.UserData
	UserRequest            = user.UserRequest
	UserResponse           = user.UserResponse

	User interface {
		RegisterUser(ctx context.Context, in *RegisterOrLoginRequest, opts ...grpc.CallOption) (*DataResponse, error)
		LoginUser(ctx context.Context, in *RegisterOrLoginRequest, opts ...grpc.CallOption) (*DataResponse, error)
		GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) RegisterUser(ctx context.Context, in *RegisterOrLoginRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RegisterUser(ctx, in, opts...)
}

func (m *defaultUser) LoginUser(ctx context.Context, in *RegisterOrLoginRequest, opts ...grpc.CallOption) (*DataResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.LoginUser(ctx, in, opts...)
}

func (m *defaultUser) GetUser(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
