// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"
	"github.com/cache-hhhhhelp/douyin-user/internal/logic"
	"github.com/cache-hhhhhelp/douyin-user/internal/svc"
	"github.com/cache-hhhhhelp/douyin-user/types/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) RegisterUser(ctx context.Context, in *user.RegisterOrLoginReq) (*user.DataResp, error) {
	l := logic.NewRegisterUserLogic(ctx, s.svcCtx)
	return l.RegisterUser(in)
}

func (s *UserServer) LoginUser(ctx context.Context, in *user.RegisterOrLoginReq) (*user.DataResp, error) {
	l := logic.NewLoginUserLogic(ctx, s.svcCtx)
	return l.LoginUser(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *user.UserReq) (*user.UserResp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) GetManyUser(ctx context.Context, in *user.ManyUserReq) (*user.ManyUserResp, error) {
	l := logic.NewGetManyUserLogic(ctx, s.svcCtx)
	return l.GetManyUser(in)
}
